#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="penpot-proxy"
MENU_ROOT="${MENU_ROOT:-$(cd "$SCRIPT_DIR" && while [[ ! -f "install_menu.sh" ]] && [[ "$PWD" != "/" ]]; do cd ..; done; pwd)}"
source "$MENU_ROOT/.lib/platform.sh"

LOG_DIR="$MENU_ROOT/.docs/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${SCRIPT_NAME}_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1

REQUIRED_BINARY="nginx"
if ! command -v "$REQUIRED_BINARY" &>/dev/null; then
    log_error "$REQUIRED_BINARY is not installed. Install it first from the menu."
    exit 1
fi

if ! docker ps --filter name=penpot-frontend --format '{{.Names}}' | grep -q penpot-frontend; then
    log_error "Penpot is not running. Install it first from Containers > Services > Penpot"
    exit 1
fi

SITES_AVAILABLE="/etc/nginx/sites-available"
SITES_ENABLED="/etc/nginx/sites-enabled"
CONF_FILE="${SITES_AVAILABLE}/penpot"

run() {
    log_info "Penpot — Nginx Reverse Proxy Configuration"
    log_info "Log file: $LOG_FILE"
    echo ""

    require_root

    mkdir -p "$SITES_AVAILABLE" "$SITES_ENABLED"

    log_step "Writing nginx proxy config to ${CONF_FILE}..."

    cat > "$CONF_FILE" <<'NGINX'
# ============================================================
# Penpot Nginx Reverse Proxy
# Generated by NinjaMenu — containers/services/penpot-proxy
# ============================================================

upstream penpot_backend {
    server 127.0.0.1:9001;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 350m;

    location / {
        proxy_pass http://penpot_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
NGINX

    log_step "Enabling site..."
    ln -sf "$CONF_FILE" "${SITES_ENABLED}/penpot"

    log_step "Testing nginx configuration..."
    nginx -t

    log_step "Reloading nginx..."
    systemctl reload nginx

    echo ""
    log_success "Nginx reverse proxy configured for Penpot."
    log_info "Config written to: ${CONF_FILE}"
    log_info "Penpot is now proxied on port 80"
}

run
