#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="postgresql-security"
MENU_ROOT="${MENU_ROOT:-$(cd "$SCRIPT_DIR" && while [[ ! -f "install_menu.sh" ]] && [[ "$PWD" != "/" ]]; do cd ..; done; pwd)}"
source "$MENU_ROOT/.lib/platform.sh"

LOG_DIR="$MENU_ROOT/.docs/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${SCRIPT_NAME}_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1

install() {
    log_info "Installing Security-Hardened PostgreSQL for Ory stack"
    log_info "Log file: $LOG_FILE"
    echo ""

    require_root

    log_step "1. Installing PostgreSQL..."
    pkg_update
    pkg_install postgresql postgresql-client openssl

    log_step "2. Starting PostgreSQL to initialise data directory..."
    systemctl enable --now postgresql

    # Wait for PostgreSQL to be ready
    local retries=0
    while ! su - postgres -c "pg_isready" &>/dev/null; do
        retries=$((retries + 1))
        if [[ $retries -ge 30 ]]; then
            log_error "PostgreSQL did not become ready in time"
            exit 1
        fi
        sleep 1
    done

    # Determine PostgreSQL data directory and config paths
    PG_VERSION=$(su - postgres -c "psql -t -c 'SHOW server_version_num'" | tr -d '[:space:]')
    PG_MAJOR=$(( PG_VERSION / 10000 ))
    PG_DATA_DIR="/etc/postgresql/${PG_MAJOR}/main"
    PG_HBA="${PG_DATA_DIR}/pg_hba.conf"
    PG_CONF="${PG_DATA_DIR}/postgresql.conf"
    PG_SSL_DIR="/etc/postgresql/${PG_MAJOR}/main/ssl"

    log_step "3. Generating self-signed SSL certificate..."
    mkdir -p "${PG_SSL_DIR}"

    openssl req -new -x509 -days 3650 -nodes \
        -out "${PG_SSL_DIR}/server.crt" \
        -keyout "${PG_SSL_DIR}/server.key" \
        -subj "/CN=postgresql-localhost/O=NinjaMenu/C=GB"

    chown postgres:postgres "${PG_SSL_DIR}/server.crt" "${PG_SSL_DIR}/server.key"
    chmod 600 "${PG_SSL_DIR}/server.key"
    chmod 644 "${PG_SSL_DIR}/server.crt"

    log_step "4. Hardening postgresql.conf..."
    # Enable SSL
    sed -i "s|^#\?ssl\s*=.*|ssl = on|" "${PG_CONF}"
    sed -i "s|^#\?ssl_cert_file\s*=.*|ssl_cert_file = '${PG_SSL_DIR}/server.crt'|" "${PG_CONF}"
    sed -i "s|^#\?ssl_key_file\s*=.*|ssl_key_file = '${PG_SSL_DIR}/server.key'|" "${PG_CONF}"

    # Bind to localhost only
    sed -i "s|^#\?listen_addresses\s*=.*|listen_addresses = 'localhost'|" "${PG_CONF}"

    # Logging
    sed -i "s|^#\?log_connections\s*=.*|log_connections = on|" "${PG_CONF}"
    sed -i "s|^#\?log_disconnections\s*=.*|log_disconnections = on|" "${PG_CONF}"
    sed -i "s|^#\?log_line_prefix\s*=.*|log_line_prefix = '%m [%p] %q%u@%d '|" "${PG_CONF}"

    # Password encryption
    sed -i "s|^#\?password_encryption\s*=.*|password_encryption = scram-sha-256|" "${PG_CONF}"

    log_step "5. Hardening pg_hba.conf..."
    # Back up original
    cp "${PG_HBA}" "${PG_HBA}.bak.$(date +%Y%m%d%H%M%S)"

    cat > "${PG_HBA}" <<'HBA'
# PostgreSQL Client Authentication Configuration (Security-Hardened)
# Generated by NinjaMenu — databases/postgresql-security
#
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local superuser access via peer (Unix socket only)
local   postgres        postgres                                peer

# Ory stack databases — local connections with scram-sha-256
host    kratos          ory_user        127.0.0.1/32            scram-sha-256
host    hydra           ory_user        127.0.0.1/32            scram-sha-256
host    keto            ory_user        127.0.0.1/32            scram-sha-256
host    kratos          ory_user        ::1/128                 scram-sha-256
host    hydra           ory_user        ::1/128                 scram-sha-256
host    keto            ory_user        ::1/128                 scram-sha-256

# Reject everything else
host    all             all             0.0.0.0/0               reject
host    all             all             ::/0                    reject
local   all             all                                     reject
HBA

    log_step "6. Creating Ory databases and user..."
    ORY_PASSWORD=$(openssl rand -hex 16)

    su - postgres -c "psql -v ON_ERROR_STOP=1" <<EOSQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'ory_user') THEN
        CREATE ROLE ory_user WITH LOGIN PASSWORD '${ORY_PASSWORD}';
    ELSE
        ALTER ROLE ory_user WITH PASSWORD '${ORY_PASSWORD}';
    END IF;
END
\$\$;
EOSQL

    for db in kratos hydra keto; do
        su - postgres -c "psql -tc \"SELECT 1 FROM pg_database WHERE datname = '${db}'\"" | \
            { grep -q 1 || su - postgres -c "createdb -O ory_user ${db}"; }
    done

    # Grant schema permissions
    for db in kratos hydra keto; do
        su - postgres -c "psql -d ${db} -c 'GRANT ALL ON SCHEMA public TO ory_user;'"
    done

    log_step "7. Restarting PostgreSQL with hardened config..."
    systemctl restart postgresql

    # Verify it came back up
    retries=0
    while ! su - postgres -c "pg_isready" &>/dev/null; do
        retries=$((retries + 1))
        if [[ $retries -ge 30 ]]; then
            log_error "PostgreSQL did not restart successfully"
            log_error "Check: journalctl -xeu postgresql"
            exit 1
        fi
        sleep 1
    done

    log_step "8. Verifying SSL is enabled..."
    SSL_STATUS=$(su - postgres -c "psql -t -c 'SHOW ssl'" | tr -d '[:space:]')
    if [[ "${SSL_STATUS}" == "on" ]]; then
        log_info "SSL: enabled"
    else
        log_warn "SSL: not active (check certificate paths)"
    fi

    # Save credentials
    CREDS_FILE="/root/.ory-postgres-credentials"
    cat > "${CREDS_FILE}" <<EOF
# Ory PostgreSQL Credentials — generated by NinjaMenu
# Date: $(date -Iseconds)
ory_user password: ${ORY_PASSWORD}

Connection strings:
  kratos: postgres://ory_user:${ORY_PASSWORD}@localhost:5432/kratos?sslmode=require
  hydra:  postgres://ory_user:${ORY_PASSWORD}@localhost:5432/hydra?sslmode=require
  keto:   postgres://ory_user:${ORY_PASSWORD}@localhost:5432/keto?sslmode=require
EOF
    chmod 600 "${CREDS_FILE}"

    echo ""
    log_success "Security-hardened PostgreSQL installed and running"
    log_info "Databases created: kratos, hydra, keto"
    log_info "User: ory_user"
    log_info "Credentials saved to: ${CREDS_FILE}"
    log_info "SSL: enabled (self-signed)"
    log_info "listen_addresses: localhost only"
    mark_installed true
}

uninstall() {
    log_info "Uninstalling PostgreSQL (security-hardened)"
    require_root

    systemctl stop postgresql 2>/dev/null || true
    systemctl disable postgresql 2>/dev/null || true
    pkg_remove postgresql postgresql-client
    apt-get autoremove -y 2>/dev/null || true
    rm -f /root/.ory-postgres-credentials

    log_info "Data directory preserved at /var/lib/postgresql/. Remove manually if desired."
    log_success "PostgreSQL uninstalled"
    mark_installed false
}

case "${1:-install}" in
    install) install ;;
    uninstall) uninstall ;;
    *) echo "Usage: $0 {install|uninstall}"; exit 1 ;;
esac
