#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="rabbitmq"
MENU_ROOT="${MENU_ROOT:-$(cd "$SCRIPT_DIR" && while [[ ! -f "install_menu.sh" ]] && [[ "$PWD" != "/" ]]; do cd ..; done; pwd)}"
source "$MENU_ROOT/.lib/platform.sh"

LOG_DIR="$MENU_ROOT/.docs/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${SCRIPT_NAME}_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1

RABBITMQ_SSL_DIR="/etc/rabbitmq/ssl"
RABBITMQ_CONF="/etc/rabbitmq/rabbitmq.conf"
CREDS_FILE="/root/.rabbitmq-credentials"

install() {
    log_info "Installing RabbitMQ with SSL/TLS"
    log_info "Log file: $LOG_FILE"
    echo ""

    require_root

    log_step "1. Adding Erlang and RabbitMQ repositories..."
    pkg_update
    pkg_install curl gnupg apt-transport-https

    # Add Erlang Solutions repo
    curl -fsSL https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | \
        gpg --dearmor -o /usr/share/keyrings/erlang-solutions.gpg 2>/dev/null || true

    # Detect distro codename (fall back to bookworm for Kali)
    CODENAME=$(lsb_release -cs 2>/dev/null || echo "bookworm")
    case "${CODENAME}" in
        kali-*) CODENAME="bookworm" ;;
    esac

    cat > /etc/apt/sources.list.d/erlang-solutions.list <<EOF
deb [signed-by=/usr/share/keyrings/erlang-solutions.gpg] https://packages.erlang-solutions.com/debian ${CODENAME} contrib
EOF

    # Add RabbitMQ official repo
    curl -fsSL https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey | \
        gpg --dearmor -o /usr/share/keyrings/rabbitmq.gpg 2>/dev/null || true

    cat > /etc/apt/sources.list.d/rabbitmq.list <<EOF
deb [signed-by=/usr/share/keyrings/rabbitmq.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/debian/ ${CODENAME} main
EOF

    log_step "2. Installing Erlang and RabbitMQ..."
    pkg_update
    pkg_install erlang-base erlang-nox rabbitmq-server

    log_step "3. Enabling management plugin..."
    rabbitmq-plugins enable rabbitmq_management
    rabbitmq-plugins enable rabbitmq_management_agent

    log_step "4. Generating self-signed TLS certificates..."
    mkdir -p "${RABBITMQ_SSL_DIR}"

    # CA key and cert
    openssl req -new -x509 -days 3650 -nodes \
        -out "${RABBITMQ_SSL_DIR}/ca_certificate.pem" \
        -keyout "${RABBITMQ_SSL_DIR}/ca_key.pem" \
        -subj "/CN=RabbitMQ-CA/O=NinjaMenu/C=GB"

    # Server key and CSR
    openssl req -new -nodes \
        -out "${RABBITMQ_SSL_DIR}/server.csr" \
        -keyout "${RABBITMQ_SSL_DIR}/server_key.pem" \
        -subj "/CN=localhost/O=NinjaMenu/C=GB"

    # Sign server cert with CA
    openssl x509 -req -days 3650 \
        -in "${RABBITMQ_SSL_DIR}/server.csr" \
        -CA "${RABBITMQ_SSL_DIR}/ca_certificate.pem" \
        -CAkey "${RABBITMQ_SSL_DIR}/ca_key.pem" \
        -CAcreateserial \
        -out "${RABBITMQ_SSL_DIR}/server_certificate.pem"

    rm -f "${RABBITMQ_SSL_DIR}/server.csr"

    chown -R rabbitmq:rabbitmq "${RABBITMQ_SSL_DIR}"
    chmod 600 "${RABBITMQ_SSL_DIR}"/*.pem

    log_step "5. Writing RabbitMQ configuration..."
    cat > "${RABBITMQ_CONF}" <<CONF
## RabbitMQ Configuration — generated by NinjaMenu
## SSL/TLS enabled

# Plain AMQP disabled (use SSL only)
listeners.tcp = none

# AMQPS (SSL) listener
listeners.ssl.default = 5671

# Management console over HTTPS
management.ssl.port = 15671
management.ssl.cacertfile = ${RABBITMQ_SSL_DIR}/ca_certificate.pem
management.ssl.certfile = ${RABBITMQ_SSL_DIR}/server_certificate.pem
management.ssl.keyfile = ${RABBITMQ_SSL_DIR}/server_key.pem

# SSL options
ssl_options.cacertfile = ${RABBITMQ_SSL_DIR}/ca_certificate.pem
ssl_options.certfile = ${RABBITMQ_SSL_DIR}/server_certificate.pem
ssl_options.keyfile = ${RABBITMQ_SSL_DIR}/server_key.pem
ssl_options.verify = verify_none
ssl_options.fail_if_no_peer_cert = false

# Logging
log.file.level = info
log.console = true
log.console.level = warning
CONF

    chown rabbitmq:rabbitmq "${RABBITMQ_CONF}"

    log_step "6. Creating admin user..."
    ADMIN_USER="ninja_admin"
    ADMIN_PASS=$(openssl rand -hex 16)

    systemctl restart rabbitmq-server

    # Wait for RabbitMQ to be ready
    local retries=0
    while ! rabbitmqctl status &>/dev/null; do
        retries=$((retries + 1))
        if [[ $retries -ge 60 ]]; then
            log_error "RabbitMQ did not start in time"
            exit 1
        fi
        sleep 2
    done

    # Create admin user and remove default guest
    rabbitmqctl add_user "${ADMIN_USER}" "${ADMIN_PASS}" 2>/dev/null || \
        rabbitmqctl change_password "${ADMIN_USER}" "${ADMIN_PASS}"
    rabbitmqctl set_user_tags "${ADMIN_USER}" administrator
    rabbitmqctl set_permissions -p / "${ADMIN_USER}" ".*" ".*" ".*"

    # Remove default guest user
    rabbitmqctl delete_user guest 2>/dev/null || true

    log_step "7. Enabling and starting service..."
    systemctl enable rabbitmq-server

    # Save credentials
    cat > "${CREDS_FILE}" <<EOF
# RabbitMQ Credentials — generated by NinjaMenu
# Date: $(date -Iseconds)
Admin user: ${ADMIN_USER}
Admin password: ${ADMIN_PASS}

Management console: https://localhost:15671
AMQPS:              amqps://localhost:5671
CA certificate:     ${RABBITMQ_SSL_DIR}/ca_certificate.pem
EOF
    chmod 600 "${CREDS_FILE}"

    log_step "8. Verifying installation..."
    rabbitmqctl status | head -5

    echo ""
    log_success "RabbitMQ installed with SSL/TLS"
    log_info "AMQPS:     amqps://localhost:5671"
    log_info "Management: https://localhost:15671"
    log_info "Admin user: ${ADMIN_USER}"
    log_info "Credentials saved to: ${CREDS_FILE}"
    log_info "Plain AMQP (5672) is disabled; all traffic uses TLS"
    mark_installed true
}

uninstall() {
    log_info "Uninstalling RabbitMQ"
    require_root

    systemctl stop rabbitmq-server 2>/dev/null || true
    systemctl disable rabbitmq-server 2>/dev/null || true
    pkg_remove rabbitmq-server
    apt-get autoremove -y 2>/dev/null || true

    rm -f /etc/apt/sources.list.d/rabbitmq.list
    rm -f /etc/apt/sources.list.d/erlang-solutions.list
    rm -f /usr/share/keyrings/rabbitmq.gpg
    rm -f /usr/share/keyrings/erlang-solutions.gpg
    rm -f "${CREDS_FILE}"

    log_info "SSL certs preserved at ${RABBITMQ_SSL_DIR}. Remove manually if desired."
    log_success "RabbitMQ uninstalled"
    mark_installed false
}

case "${1:-install}" in
    install) install ;;
    uninstall) uninstall ;;
    *) echo "Usage: $0 {install|uninstall}"; exit 1 ;;
esac
