#!/bin/bash
# Linux implementation — do NOT add YAML headers here (use meta.yaml)
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/_common.sh"
exec > >(tee -a "$LOG_FILE") 2>&1

require_linux "Hyprland requires Linux"

HYPRLAND_PACKAGES=(
    hyprland
    waybar
    wofi
    mako-notifier
    thunar
    network-manager-gnome
    pipewire
    wireplumber
    xdg-desktop-portal-hyprland
)

REAL_USER="${SUDO_USER:-$USER}"
REAL_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)
HYPR_CONFIG_DIR="${REAL_HOME}/.config/hypr"

install() {
    log_info "Installing Hyprland..."
    log_info "Log file: $LOG_FILE"
    echo ""

    require_root

    log_step "Updating package list..."
    pkg_update

    # Check if hyprland is available in the repos; if not, add a source
    log_step "Checking if Hyprland is available in repositories..."
    if ! apt-cache show hyprland &>/dev/null; then
        log_info "Hyprland not found in current repos — adding package source..."

        # Detect distro to pick the right repo strategy
        local distro_id
        distro_id=$(. /etc/os-release && echo "$ID")

        case "$distro_id" in
            ubuntu|kali|debian)
                log_step "Adding Debian Sid repo with low-priority pin for Hyprland..."
                cat > /etc/apt/sources.list.d/debian-sid-hyprland.list <<'SIDREPO'
# Added by ninja-toolbox for Hyprland packages
deb http://deb.debian.org/debian sid main
SIDREPO
                # Pin Sid to very low priority so it only provides explicitly requested packages
                cat > /etc/apt/preferences.d/debian-sid-hyprland.pref <<'SIDPIN'
# Only pull packages from Sid when explicitly requested (-t sid)
Package: *
Pin: release n=sid
Pin-Priority: 50
SIDPIN
                pkg_update
                ;;
            *)
                log_error "Hyprland is not available in your current repositories."
                echo ""
                echo "Unsupported distro ($distro_id) for automatic repo setup."
                echo "Manual installation options:"
                echo "  1. https://wiki.hyprland.org/Getting-Started/Installation/"
                echo "  2. Build from source: https://github.com/hyprwm/Hyprland"
                echo ""
                exit 1
                ;;
        esac

        # Verify it's now available
        if ! apt-cache show hyprland &>/dev/null; then
            log_error "Hyprland still not available after adding repo."
            echo "Check your network connection and try again."
            exit 1
        fi
        log_success "Hyprland package source added successfully"
    fi

    log_step "Installing Hyprland and companion packages..."
    # If we added the Sid repo, use -t sid to pull from it
    if [[ -f /etc/apt/sources.list.d/debian-sid-hyprland.list ]]; then
        apt-get install -y -t sid "${HYPRLAND_PACKAGES[@]}"
    else
        pkg_install "${HYPRLAND_PACKAGES[@]}"
    fi

    log_step "Creating default Hyprland configuration..."
    mkdir -p "$HYPR_CONFIG_DIR"

    if [[ ! -f "${HYPR_CONFIG_DIR}/hyprland.conf" ]]; then
        cat > "${HYPR_CONFIG_DIR}/hyprland.conf" << 'HYPRCONF'
# Hyprland configuration — generated by ninja-toolbox
# Full reference: https://wiki.hyprland.org/Configuring/

monitor = ,preferred,auto,1

# Default programs
$terminal = thunar
$menu = wofi --show drun

# Autostart
exec-once = waybar
exec-once = mako

# Environment variables
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct

# Input
input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

# General appearance
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(fca311ee) rgba(e5e5e5ee) 45deg
    col.inactive_border = rgba(14213daa)
    layout = dwindle
}

# Decorations
decoration {
    rounding = 8
    blur {
        enabled = true
        size = 3
        passes = 1
    }
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
}

# Animations
animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# Layout
dwindle {
    pseudotile = true
    preserve_split = true
}

# Keybinds
$mainMod = SUPER

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod SHIFT, E, exit,
bind = $mainMod, V, togglefloating,
bind = $mainMod, D, exec, $menu
bind = $mainMod, P, pseudo,
bind = $mainMod, J, togglesplit,

# Move focus
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Mouse binds
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
HYPRCONF
        chown -h "${REAL_USER}:${REAL_USER}" "${HYPR_CONFIG_DIR}/hyprland.conf"
        log_info "Default configuration written to ${HYPR_CONFIG_DIR}/hyprland.conf"
    else
        log_info "Existing Hyprland config found, skipping config generation"
    fi

    # Fix ownership of config directory
    chown -Rh "${REAL_USER}:${REAL_USER}" "${HYPR_CONFIG_DIR}"

    # Create wayland session desktop file if not provided by the package
    log_step "Ensuring Hyprland session entry exists..."
    if [[ ! -f /usr/share/wayland-sessions/hyprland.desktop ]]; then
        mkdir -p /usr/share/wayland-sessions
        cat > /usr/share/wayland-sessions/hyprland.desktop << 'DESKTOP'
[Desktop Entry]
Name=Hyprland
Comment=Dynamic tiling Wayland compositor
Exec=Hyprland
Type=Application
DESKTOP
        log_info "Created /usr/share/wayland-sessions/hyprland.desktop"
    fi

    echo ""
    log_success "Hyprland installed successfully!"
    echo ""
    echo "Post-install notes:"
    echo "  - Config: ${HYPR_CONFIG_DIR}/hyprland.conf"
    echo "  - Select 'Hyprland' from your display manager session list"
    echo "  - Or start from TTY with: Hyprland"
    echo "  - Key bindings: SUPER+Return=terminal, SUPER+D=launcher, SUPER+Q=close"
    echo ""

    mark_installed true
}

uninstall() {
    log_info "Removing Hyprland..."

    require_root

    log_step "Removing Hyprland packages..."
    apt-get remove -y "${HYPRLAND_PACKAGES[@]}" 2>/dev/null || true
    apt-get autoremove -y

    log_step "Removing Hyprland repo sources if added by ninja-toolbox..."
    rm -f /etc/apt/sources.list.d/debian-sid-hyprland.list
    rm -f /etc/apt/preferences.d/debian-sid-hyprland.pref

    log_step "Removing session entry..."
    rm -f /usr/share/wayland-sessions/hyprland.desktop

    echo ""
    log_success "Hyprland removed."
    log_info "User config at ${HYPR_CONFIG_DIR} has NOT been removed."
    log_info "To remove config: rm -rf ${HYPR_CONFIG_DIR}"

    mark_installed false
}

ACTION="${1:-install}"
case "$ACTION" in
    install) install ;;
    uninstall) uninstall ;;
    *) echo "Usage: $0 {install|uninstall}"; exit 1 ;;
esac
