#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="portainer-proxy"
MENU_ROOT="${MENU_ROOT:-$(cd "$SCRIPT_DIR" && while [[ ! -f "install_menu.sh" ]] && [[ "$PWD" != "/" ]]; do cd ..; done; pwd)}"
source "$MENU_ROOT/.lib/platform.sh"

LOG_DIR="$MENU_ROOT/.docs/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${SCRIPT_NAME}_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1

REQUIRED_BINARY="nginx"
if ! command -v "$REQUIRED_BINARY" &>/dev/null; then
    log_error "$REQUIRED_BINARY is not installed. Install it first from the menu."
    exit 1
fi

if ! docker ps --filter name=portainer --format '{{.Names}}' | grep -q portainer; then
    log_error "Portainer is not running. Install it first from Containers > Runtime > Portainer"
    exit 1
fi

SITES_AVAILABLE="/etc/nginx/sites-available"
SITES_ENABLED="/etc/nginx/sites-enabled"
CONF_FILE="${SITES_AVAILABLE}/portainer"

run() {
    log_info "Portainer — Nginx Reverse Proxy Configuration"
    log_info "Log file: $LOG_FILE"
    echo ""

    require_root

    # Detect LAN IP for access URL
    LAN_IP="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}')"
    if [[ -z "$LAN_IP" ]]; then
        LAN_IP="$(hostname -I | awk '{print $1}')"
    fi
    if [[ -z "$LAN_IP" ]]; then
        LAN_IP="127.0.0.1"
        log_warn "Could not detect LAN IP, defaulting to 127.0.0.1"
    fi
    log_info "Detected LAN IP: ${LAN_IP}"

    mkdir -p "$SITES_AVAILABLE" "$SITES_ENABLED"

    log_step "Writing nginx proxy config to ${CONF_FILE}..."

    cat > "$CONF_FILE" <<'NGINX'
# ============================================================
# Portainer Nginx Reverse Proxy
# Generated by NinjaMenu — containers/runtime/portainer-proxy
# ============================================================

upstream portainer_backend {
    server 127.0.0.1:9443;
}

server {
    listen 8443;
    server_name _;

    location / {
        proxy_pass https://portainer_backend;
        proxy_ssl_verify off;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
NGINX

    log_step "Enabling site..."
    ln -sf "$CONF_FILE" "${SITES_ENABLED}/portainer"

    log_step "Testing nginx configuration..."
    nginx -t

    log_step "Reloading nginx..."
    systemctl reload nginx

    echo ""
    log_success "Nginx reverse proxy configured for Portainer."
    log_info "Config written to: ${CONF_FILE}"
    log_info "Portainer is now proxied at: http://${LAN_IP}:8443"
}

run
