#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="squid"
MENU_ROOT="${MENU_ROOT:-$(cd "$SCRIPT_DIR" && while [[ ! -f "install_menu.sh" ]] && [[ "$PWD" != "/" ]]; do cd ..; done; pwd)}"
source "$MENU_ROOT/.lib/platform.sh"

LOG_DIR="$MENU_ROOT/.docs/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${SCRIPT_NAME}_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1

SQUID_CONF="/etc/squid/squid.conf"

install() {
    log_info "Installing Squid Proxy Server"
    log_info "Log file: $LOG_FILE"
    echo ""

    require_root

    log_step "1. Installing Squid..."
    pkg_update
    pkg_install squid

    log_step "2. Backing up default configuration..."
    if [[ -f "${SQUID_CONF}" ]]; then
        cp "${SQUID_CONF}" "${SQUID_CONF}.bak.$(date +%Y%m%d%H%M%S)"
    fi

    log_step "3. Writing Squid configuration..."
    cat > "${SQUID_CONF}" <<'SQUID'
# Squid Proxy Configuration — generated by NinjaMenu
# See: http://www.squid-cache.org/Doc/config/

# --- ACL Definitions ---
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10

acl SSL_ports port 443
acl Safe_ports port 80          # http
acl Safe_ports port 21          # ftp
acl Safe_ports port 443         # https
acl Safe_ports port 70          # gopher
acl Safe_ports port 210         # wais
acl Safe_ports port 1025-65535  # unregistered ports
acl Safe_ports port 280         # http-mgmt
acl Safe_ports port 488         # gss-http
acl Safe_ports port 591         # filemaker
acl Safe_ports port 777         # multiling http

acl CONNECT method CONNECT

# --- Access Rules ---
# Deny requests to unsafe ports
http_access deny !Safe_ports

# Deny CONNECT to non-SSL ports
http_access deny CONNECT !SSL_ports

# Only allow cachemgr from localhost
http_access allow localhost manager
http_access deny manager

# Allow local networks
http_access allow localnet
http_access allow localhost

# Deny everything else
http_access deny all

# --- Listener ---
http_port 3128

# --- Cache Configuration ---
# 256 MB disk cache, 16/256 L1/L2 directories
cache_dir ufs /var/spool/squid 256 16 256

# Memory cache: 64 MB
cache_mem 64 MB

# Maximum object size in memory: 512 KB
maximum_object_size_in_memory 512 KB

# Maximum cached object: 16 MB
maximum_object_size 16 MB

# --- Logging ---
access_log daemon:/var/log/squid/access.log squid
cache_log /var/log/squid/cache.log
cache_store_log daemon:/var/log/squid/store.log

# Log format includes response time
logformat squid %ts.%03tu %6tr %>a %Ss/%03>Hs %<st %rm %ru %[un %Sh/%<a %mt

# --- Privacy ---
# Suppress Squid version in error pages and headers
httpd_suppress_version_string on

# Remove forwarded-for header
forwarded_for delete

# Remove via header
via off

# --- Timeouts ---
connect_timeout 30 seconds
read_timeout 60 seconds
request_timeout 30 seconds

# --- Misc ---
coredump_dir /var/spool/squid
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
SQUID

    log_step "4. Initialising cache directories..."
    squid -z 2>/dev/null || true

    log_step "5. Testing configuration..."
    squid -k parse

    log_step "6. Enabling and starting Squid..."
    systemctl enable --now squid

    log_step "7. Verifying installation..."
    squid -v | head -1
    systemctl is-active squid

    echo ""
    log_success "Squid Proxy installed and running"
    log_info "HTTP Proxy: localhost:3128"
    log_info "Config:     ${SQUID_CONF}"
    log_info "Access log: /var/log/squid/access.log"
    log_info ""
    log_info "To use: export http_proxy=http://localhost:3128"
    mark_installed true
}

uninstall() {
    log_info "Uninstalling Squid Proxy"
    require_root

    systemctl stop squid 2>/dev/null || true
    systemctl disable squid 2>/dev/null || true
    pkg_remove squid
    apt-get autoremove -y 2>/dev/null || true

    log_info "Cache and logs preserved at /var/spool/squid and /var/log/squid"
    log_success "Squid Proxy uninstalled"
    mark_installed false
}

case "${1:-install}" in
    install) install ;;
    uninstall) uninstall ;;
    *) echo "Usage: $0 {install|uninstall}"; exit 1 ;;
esac
