#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="nftables-hardened"
MENU_ROOT="${MENU_ROOT:-$(cd "$SCRIPT_DIR" && while [[ ! -f "install_menu.sh" ]] && [[ "$PWD" != "/" ]]; do cd ..; done; pwd)}"
source "$MENU_ROOT/.lib/platform.sh"

LOG_DIR="$MENU_ROOT/.docs/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${SCRIPT_NAME}_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1

REQUIRED_BINARY="nft"
if ! command -v "$REQUIRED_BINARY" &>/dev/null; then
    log_error "$REQUIRED_BINARY is not installed. Install nftables first."
    exit 1
fi

CONF_FILE="/etc/nftables.conf"

run() {
    log_info "nftables — Hardened Firewall Rules"
    log_info "Includes all basic rules plus SYN flood protection, SSH/HTTP rate"
    log_info "limiting, ICMP throttling, scan blocking, and dropped packet logging."
    log_info "Log file: $LOG_FILE"
    echo ""

    require_root

    # Back up existing config if present
    if [[ -f "$CONF_FILE" ]]; then
        BACKUP="${CONF_FILE}.bak.$(date +%Y%m%d_%H%M%S)"
        log_step "Backing up existing config to ${BACKUP}..."
        cp "$CONF_FILE" "$BACKUP"
    fi

    log_step "Flushing existing nftables ruleset..."
    nft flush ruleset

    log_step "Writing hardened firewall rules to ${CONF_FILE}..."

    cat > "$CONF_FILE" <<'NFT'
#!/usr/sbin/nft -f
# ============================================================
# nftables Hardened Firewall
# Generated by NinjaMenu — security/configuration/nftables-hardened
# Includes basic rules + SYN flood / scan / rate-limit protections
# ============================================================

flush ruleset

table inet filter {

    chain input {
        type filter hook input priority 0; policy drop;

        # --- Loopback ----------------------------------------
        iif "lo" accept

        # --- Connection tracking -----------------------------
        ct state established,related accept

        # --- Drop invalid packets ----------------------------
        ct state invalid log prefix "nftables-drop: " drop

        # --- SYN flood protection ----------------------------
        # New TCP connections must have SYN flag set
        tcp flags & (fin|syn|rst|ack) != syn ct state new drop

        # --- Block christmas tree packets --------------------
        tcp flags & (fin|syn|rst|psh|ack|urg) == fin|syn|rst|psh|ack|urg log prefix "nftables-drop: " drop

        # --- Block null packets ------------------------------
        tcp flags & (fin|syn|rst|psh|ack|urg) == 0x0 log prefix "nftables-drop: " drop

        # --- ICMP rate limiting (5/second) -------------------
        ip protocol icmp limit rate 5/second burst 10 packets accept
        ip6 nexthdr icmpv6 limit rate 5/second burst 10 packets accept
        ip protocol icmp drop
        ip6 nexthdr icmpv6 drop

        # --- SSH rate limiting (3 new connections/minute per IP) ---
        tcp dport 22 ct state new limit rate 3/minute burst 5 packets accept
        tcp dport 22 ct state new log prefix "nftables-drop: " drop

        # --- HTTP/HTTPS rate limiting (25 new connections/second per IP) ---
        tcp dport 80 ct state new limit rate 25/second burst 50 packets accept
        tcp dport 80 ct state new log prefix "nftables-drop: " drop
        tcp dport 443 ct state new limit rate 25/second burst 50 packets accept
        tcp dport 443 ct state new log prefix "nftables-drop: " drop

        # --- Allow remaining established SSH/HTTP/HTTPS ------
        tcp dport { 22, 80, 443 } accept

        # --- Log and drop everything else --------------------
        log prefix "nftables-drop: " drop
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
        log prefix "nftables-drop: " drop
    }

    chain output {
        type filter hook output priority 0; policy accept;

        # Allow loopback
        oif "lo" accept

        # Allow established and related
        ct state established,related accept

        # Allow DNS (53)
        tcp dport 53 accept
        udp dport 53 accept

        # Allow HTTP/HTTPS outbound
        tcp dport { 80, 443 } accept

        # Allow NTP (123)
        udp dport 123 accept
    }
}
NFT

    log_step "Reloading nftables ruleset..."
    nft -f "$CONF_FILE"

    log_step "Enabling nftables service..."
    systemctl enable nftables 2>/dev/null || true

    log_step "Verifying ruleset..."
    nft list ruleset

    echo ""
    log_success "Hardened firewall rules applied."
    log_info "Config written to: ${CONF_FILE}"
    echo ""
    log_info "Protections enabled:"
    log_info "  - SYN flood protection (new TCP must have SYN)"
    log_info "  - SSH rate limit: 3 new connections/minute per IP"
    log_info "  - HTTP/HTTPS rate limit: 25 new connections/second per IP"
    log_info "  - ICMP rate limit: 5/second"
    log_info "  - Christmas tree and null packet blocking"
    log_info "  - Invalid packet dropping"
    log_info "  - All dropped packets logged with prefix 'nftables-drop: '"
    log_info ""
    log_info "Monitor drops: journalctl -k --grep='nftables-drop'"
}

run
