#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="nftables-basic"
MENU_ROOT="${MENU_ROOT:-$(cd "$SCRIPT_DIR" && while [[ ! -f "install_menu.sh" ]] && [[ "$PWD" != "/" ]]; do cd ..; done; pwd)}"
source "$MENU_ROOT/.lib/platform.sh"

LOG_DIR="$MENU_ROOT/.docs/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${SCRIPT_NAME}_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1

REQUIRED_BINARY="nft"
if ! command -v "$REQUIRED_BINARY" &>/dev/null; then
    log_error "$REQUIRED_BINARY is not installed. Install nftables first."
    exit 1
fi

CONF_FILE="/etc/nftables.conf"

run() {
    log_info "nftables — Basic Firewall Rules"
    log_info "Allows SSH, HTTP, HTTPS inbound; common outbound; drops the rest."
    log_info "Log file: $LOG_FILE"
    echo ""

    require_root

    # Back up existing config if present
    if [[ -f "$CONF_FILE" ]]; then
        BACKUP="${CONF_FILE}.bak.$(date +%Y%m%d_%H%M%S)"
        log_step "Backing up existing config to ${BACKUP}..."
        cp "$CONF_FILE" "$BACKUP"
    fi

    log_step "Flushing existing nftables ruleset..."
    nft flush ruleset

    log_step "Writing basic firewall rules to ${CONF_FILE}..."

    cat > "$CONF_FILE" <<'NFT'
#!/usr/sbin/nft -f
# ============================================================
# nftables Basic Firewall
# Generated by NinjaMenu — security/configuration/nftables-basic
# ============================================================

flush ruleset

table inet filter {

    chain input {
        type filter hook input priority 0; policy drop;

        # Allow loopback traffic
        iif "lo" accept

        # Allow established and related connections
        ct state established,related accept

        # Drop invalid packets
        ct state invalid drop

        # Allow SSH (port 22)
        tcp dport 22 accept

        # Allow HTTP (port 80)
        tcp dport 80 accept

        # Allow HTTPS (port 443)
        tcp dport 443 accept

        # Allow ICMP (ping)
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
    }

    chain output {
        type filter hook output priority 0; policy accept;

        # Allow loopback
        oif "lo" accept

        # Allow established and related
        ct state established,related accept

        # Allow DNS (53)
        tcp dport 53 accept
        udp dport 53 accept

        # Allow HTTP/HTTPS outbound
        tcp dport { 80, 443 } accept

        # Allow NTP (123)
        udp dport 123 accept
    }
}
NFT

    log_step "Reloading nftables ruleset..."
    nft -f "$CONF_FILE"

    log_step "Enabling nftables service..."
    systemctl enable nftables 2>/dev/null || true

    log_step "Verifying ruleset..."
    nft list ruleset

    echo ""
    log_success "Basic firewall rules applied."
    log_info "Config written to: ${CONF_FILE}"
    log_info "Allowed inbound: SSH (22), HTTP (80), HTTPS (443), ICMP"
    log_info "Allowed outbound: DNS (53), HTTP (80), HTTPS (443), NTP (123)"
    log_info "Default policy: DROP"
}

run
