#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="nginx-extreme"
MENU_ROOT="${MENU_ROOT:-$(cd "$SCRIPT_DIR" && while [[ ! -f "install_menu.sh" ]] && [[ "$PWD" != "/" ]]; do cd ..; done; pwd)}"
source "$MENU_ROOT/.lib/platform.sh"

LOG_DIR="$MENU_ROOT/.docs/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${SCRIPT_NAME}_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1

REQUIRED_BINARY="nginx"
if ! command -v "$REQUIRED_BINARY" &>/dev/null; then
    log_error "$REQUIRED_BINARY is not installed. Install it first from the menu."
    exit 1
fi

CONF_FILE="/etc/nginx/conf.d/security-extreme.conf"
MODERATE_CONF="/etc/nginx/conf.d/security-moderate.conf"
LIGHT_CONF="/etc/nginx/conf.d/security-light.conf"

run() {
    log_info "Nginx — Extreme Security Hardening"
    log_info "Full lockdown: HSTS preload, strict CSP, WAF rules, bot blocking,"
    log_info "attack pattern filtering, connection limits, and request size limits."
    log_info "Log file: $LOG_FILE"
    echo ""

    require_root

    # Remove lower-tier configs (extreme supersedes them)
    if [[ -f "$LIGHT_CONF" ]]; then
        log_step "Removing light hardening config (superseded)..."
        rm -f "$LIGHT_CONF"
    fi
    if [[ -f "$MODERATE_CONF" ]]; then
        log_step "Removing moderate hardening config (superseded)..."
        rm -f "$MODERATE_CONF"
    fi

    log_step "Writing extreme security config to ${CONF_FILE}..."

    cat > "$CONF_FILE" <<'NGINX'
# ============================================================
# Nginx Extreme Security Hardening
# Generated by NinjaMenu — security/configuration/nginx-extreme
# Includes all light + moderate protections plus full lockdown
# ============================================================

# --- Light protections (included) ----------------------------

# Hide nginx version
server_tokens off;

# Prevent MIME-type sniffing
add_header X-Content-Type-Options "nosniff" always;

# Prevent clickjacking
add_header X-Frame-Options "SAMEORIGIN" always;

# Disable directory listing
autoindex off;

# --- Moderate protections (included) -------------------------

# Rate limiting zones
limit_req_zone $binary_remote_addr zone=general:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;

# SSL/TLS hardening — TLS 1.2+ only
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;
ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305';
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 1d;
ssl_session_tickets off;

# Referrer and permissions policy
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=()" always;

# HTTP method restriction map
map $request_method $bad_method {
    default 1;
    GET     0;
    POST    0;
    HEAD    0;
}

# --- Extreme protections (new) -------------------------------

# HSTS with preload — 2 year max-age, include subdomains
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

# Strict Content-Security-Policy with nonce support
# Replace $CSP_NONCE in your app/server block with a per-request nonce
add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'self'; base-uri 'self'; form-action 'self'" always;

# Cross-Origin policies
add_header Cross-Origin-Embedder-Policy "require-corp" always;
add_header Cross-Origin-Opener-Policy "same-origin" always;
add_header Cross-Origin-Resource-Policy "same-origin" always;

# Request body size limit (10MB)
client_max_body_size 10m;

# Connection limits per IP
limit_conn_zone $binary_remote_addr zone=conn_per_ip:10m;

# --- ModSecurity / Coraza WAF --------------------------------
# Uncomment the following if the modsecurity module is loaded:
# modsecurity on;
# modsecurity_rules_file /etc/nginx/modsecurity/modsecurity.conf;

# --- Bad bot / scanner blocking ------------------------------
map $http_user_agent $bad_bot {
    default 0;
    ~*(?:sqlmap|nikto|nessus|openvas|w3af|skipfish|havij)   1;
    ~*(?:masscan|zgrab|gobuster|dirbuster|ffuf|wfuzz)       1;
    ~*(?:scrapy|python-requests/2|go-http-client|libwww)    1;
    ""                                                       1;
}
# In server blocks, add: if ($bad_bot) { return 403; }

# --- Attack pattern blocking ---------------------------------
# Use these location blocks inside your server blocks:
#
# # Block SQL injection attempts
# location ~* "(union\s+select|select\s+from|insert\s+into|drop\s+table|update\s+set)" {
#     return 403;
# }
#
# # Block XSS attempts
# location ~* "(<script|javascript:|on\w+\s*=)" {
#     return 403;
# }
#
# # Block path traversal attempts
# location ~* "(\.\.\/|\.\.\\)" {
#     return 403;
# }
#
# # Block common vulnerability scanners
# location ~* "(\/wp-admin|\/wp-login|\/administrator|\/phpmyadmin)" {
#     return 403;
# }

# --- GeoIP blocking (placeholder) ----------------------------
# Requires ngx_http_geoip2_module and MaxMind GeoLite2 database.
# 1. Install: apt install libnginx-mod-http-geoip2
# 2. Download GeoLite2 DB: https://dev.maxmind.com/geoip/geolite2-free-geolocation-data
# 3. Uncomment and configure:
#
# geoip2 /usr/share/GeoIP/GeoLite2-Country.mmdb {
#     auto_reload 60m;
#     $geoip2_metadata_country_build metadata build_epoch;
#     $geoip2_data_country_iso default=XX source=$remote_addr country iso_code;
# }
#
# map $geoip2_data_country_iso $allowed_country {
#     default no;
#     GB yes;
#     US yes;
#     DE yes;
#     # Add allowed countries above
# }
# In server blocks, add: if ($allowed_country = no) { return 403; }
NGINX

    log_step "Testing nginx configuration..."
    nginx -t

    log_step "Reloading nginx..."
    systemctl reload nginx

    echo ""
    log_success "Extreme security hardening applied to nginx."
    log_info "Config written to: ${CONF_FILE}"
    echo ""
    log_info "IMPORTANT — Add the following inside each server block:"
    log_info "  # Enforce HTTP method restriction"
    log_info "  if (\$bad_method) { return 405; }"
    log_info ""
    log_info "  # Block bad bots"
    log_info "  if (\$bad_bot) { return 403; }"
    log_info ""
    log_info "  # Rate limiting"
    log_info "  limit_req zone=general burst=20 nodelay;"
    log_info "  limit_conn conn_per_ip 50;"
    log_info ""
    log_info "  # For login endpoints:"
    log_info "  limit_req zone=login burst=5 nodelay;"
    log_info ""
    log_info "See the config file for attack pattern location blocks and GeoIP setup."
}

run
