#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="nginx-moderate"
MENU_ROOT="${MENU_ROOT:-$(cd "$SCRIPT_DIR" && while [[ ! -f "install_menu.sh" ]] && [[ "$PWD" != "/" ]]; do cd ..; done; pwd)}"
source "$MENU_ROOT/.lib/platform.sh"

LOG_DIR="$MENU_ROOT/.docs/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${SCRIPT_NAME}_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1

REQUIRED_BINARY="nginx"
if ! command -v "$REQUIRED_BINARY" &>/dev/null; then
    log_error "$REQUIRED_BINARY is not installed. Install it first from the menu."
    exit 1
fi

CONF_FILE="/etc/nginx/conf.d/security-moderate.conf"
LIGHT_CONF="/etc/nginx/conf.d/security-light.conf"

run() {
    log_info "Nginx — Moderate Security Hardening"
    log_info "Includes all light protections plus rate limiting, SSL hardening,"
    log_info "additional headers, and HTTP method restrictions."
    log_info "Log file: $LOG_FILE"
    echo ""

    require_root

    # Remove light config if it exists (moderate supersedes it)
    if [[ -f "$LIGHT_CONF" ]]; then
        log_step "Removing light hardening config (superseded by moderate)..."
        rm -f "$LIGHT_CONF"
    fi

    log_step "Writing moderate security config to ${CONF_FILE}..."

    cat > "$CONF_FILE" <<'NGINX'
# ============================================================
# Nginx Moderate Security Hardening
# Generated by NinjaMenu — security/configuration/nginx-moderate
# Includes all light protections plus additional hardening
# ============================================================

# --- Light protections (included) ----------------------------

# Hide nginx version in response headers and error pages
server_tokens off;

# Prevent MIME-type sniffing
add_header X-Content-Type-Options "nosniff" always;

# Prevent clickjacking — only allow same-origin framing
add_header X-Frame-Options "SAMEORIGIN" always;

# Disable directory listing globally
autoindex off;

# --- Rate limiting -------------------------------------------

# General request rate limit: 10 requests/second per IP
limit_req_zone $binary_remote_addr zone=general:10m rate=10r/s;

# --- SSL/TLS hardening --------------------------------------

# Only allow TLS 1.2 and 1.3
ssl_protocols TLSv1.2 TLSv1.3;

# Strong cipher suite — prefer server-side ordering
ssl_prefer_server_ciphers on;
ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305';

# SSL session caching for performance
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 1d;
ssl_session_tickets off;

# --- Additional security headers -----------------------------

# Control referrer information sent with requests
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# Restrict browser features/APIs
add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=()" always;

# Basic Content Security Policy — restrict to same origin
add_header Content-Security-Policy "default-src 'self'" always;

# --- HTTP method restriction ---------------------------------
# Only allow GET, POST, and HEAD; reject everything else.
# Place this in your server blocks or use the map below in server context:
#   if ($request_method !~ ^(GET|POST|HEAD)$) { return 405; }
# The map approach (preferred for http context):
map $request_method $bad_method {
    default 0;
    GET     0;
    POST    0;
    HEAD    0;
}
# In server blocks, add: if ($bad_method) { return 405; }
NGINX

    log_step "Testing nginx configuration..."
    nginx -t

    log_step "Reloading nginx..."
    systemctl reload nginx

    echo ""
    log_success "Moderate security hardening applied to nginx."
    log_info "Config written to: ${CONF_FILE}"
    log_info ""
    log_info "NOTE: To enforce HTTP method restriction, add the following"
    log_info "inside each server block:"
    log_info "  if (\$bad_method) { return 405; }"
    log_info ""
    log_info "To apply rate limiting, add inside your server/location blocks:"
    log_info "  limit_req zone=general burst=20 nodelay;"
}

run
