#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="nginx-light"
MENU_ROOT="${MENU_ROOT:-$(cd "$SCRIPT_DIR" && while [[ ! -f "install_menu.sh" ]] && [[ "$PWD" != "/" ]]; do cd ..; done; pwd)}"
source "$MENU_ROOT/.lib/platform.sh"

LOG_DIR="$MENU_ROOT/.docs/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${SCRIPT_NAME}_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1

REQUIRED_BINARY="nginx"
if ! command -v "$REQUIRED_BINARY" &>/dev/null; then
    log_error "$REQUIRED_BINARY is not installed. Install it first from the menu."
    exit 1
fi

CONF_FILE="/etc/nginx/conf.d/security-light.conf"

run() {
    log_info "Nginx — Light Security Hardening"
    log_info "Applies basic security headers and hides server version."
    log_info "Log file: $LOG_FILE"
    echo ""

    require_root

    log_step "Writing light security config to ${CONF_FILE}..."

    cat > "$CONF_FILE" <<'NGINX'
# ============================================================
# Nginx Light Security Hardening
# Generated by NinjaMenu — security/configuration/nginx-light
# ============================================================

# Hide nginx version in response headers and error pages
server_tokens off;

# Prevent MIME-type sniffing
add_header X-Content-Type-Options "nosniff" always;

# Prevent clickjacking — only allow same-origin framing
add_header X-Frame-Options "SAMEORIGIN" always;

# Disable directory listing globally
autoindex off;
NGINX

    log_step "Testing nginx configuration..."
    nginx -t

    log_step "Reloading nginx..."
    systemctl reload nginx

    echo ""
    log_success "Light security hardening applied to nginx."
    log_info "Config written to: ${CONF_FILE}"
}

run
